apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ./default-storage-class-nfs.yaml

helmCharts: # TODO: Update to reference csi-nfs
  - name: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    version: 4.11.0
    releaseName: csi-driver-nfs
    namespace: kube-system
    valuesFile: helm-values.yaml
