apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "https://k8s-homelab-kv.vault.azure.net/"
      tenantId: "50cae205-b018-411d-a85e-78b437e19e07"
      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets

