apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - ./namespace.yaml

helmCharts:
  - name: external-secrets
    chartPath: ../charts/external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: helm-values.yaml
