apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/schwja04/k8s-homelab
    path: apps/infrastructure/csi-nfs/overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
