apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 72.5.2
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: helm-values.yaml
    includeCRDs: true
