apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-production
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/schwja04/k8s-homelab
    path: apps/shared/external-secrets/overlays/production
    targetRevision: HEAD
    kustomize:
      buildOptions:
        - --enable-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
